### ISSUE TITLE
import GraphViz from a Framework leads to " cannot find 'Process' in scope"

### ISSUE THREAD

**Issue by maxwacker** [SwiftDocOrg/GraphViz#9] opened 2020-11-15 17:04 UTC
On Xcode 12.2 (didn't try on other version), when importing GraphViz from a module (framework target, not app target)
I got the this very weird build error :
Graph+Rendering.swift:7:16: error: cannot find 'Process' in scope
    let task = Process()

I attached a very small Xcode project reproducing the issue :
[GraphViz_In_Module_Issue.zip](https://github.com/SwiftDocOrg/GraphViz/files/5542769/GraphViz_In_Module_Issue.zip)

**Comment by mattt** [comment] 2020-11-16 17:47
Sorry, but I can't reproduce this locally on macOS 10.15.7 and Xcode 12.2. After changing platform target to 10.15 and signing with my developer account team, I'm able to build and run without a problem:

```
digraph {
  a -> b
  a -> c
  b -> c [constraint=false]
}
Program ended with exit code: 0
```

**Comment by mattt** [comment] 2020-11-16 17:49
The error you're seeing suggests that Xcode is having problems with `Foundation`, the framework that provides the `Process` APIs. #10 updates CI to test Big Sur as well, to make sure this isn't an issue specific to the new OS release.

**Comment by maxwacker** [comment] 2020-11-16 18:12
With platform target 10.15, It builds successfully.
It's an acceptable workaround for me right now (waiting for fixes on Big Sur side).

Thanks a lot for the time you spent on this.

**Comment by mattt** [comment] 2020-11-16 18:28
@maxwacker FWIW, CI is [passing](https://github.com/SwiftDocOrg/GraphViz/runs/1407868806?check_suite_focus=true) on Big Sur, so it may be something specific to your project or difference between Swift Package Manager and conventional Xcode projects.

Closing this for now, unless you have any other updates. I'd gladly accept a PR with a failing test case for any problems you identify.

**Closed as completed** 2020-11-16 18:29 UTC
